import { gsap } from 'gsap';
import { SplitText } from "../../gsap/package/SplitText";
import { ScrollTrigger } from '../../gsap/package/ScrollTrigger'; 
import { DrawSVGPlugin } from "../../gsap/package/DrawSVGPlugin";
import onLoad from './on-load.js';
import menu from './menu.js';
import section1 from './section1.js';
import section2 from './section2.js';
import section3 from './section3.js';
import section4 from './Section4.js';
import Variables from './Variables';
import * as THREE from './THREE.js';
import { NoToneMapping } from 'three';
import '../css/style.css';
import micelle from '../../static/models/GLB/micelle.glb';
